# Generated by Django 4.1.1 on 2022-09-14 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField(max_length=1000)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, unique=True)),
                ('slug', models.CharField(max_length=80, unique=True)),
                ('body', models.TextField(max_length=10000)),
                ('keywords', models.TextField(max_length=100)),
                ('description', models.TextField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
