# Generated by Django 4.0.4 on 2022-09-26 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unitymed', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['-date']},
        ),
    ]
