# Generated by Django 4.1.1 on 2023-03-02 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unitymed', '0002_alter_service_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField(max_length=5000)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
