# Generated by Django 4.1.1 on 2023-03-02 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unitymed', '0003_pharmacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='image_url',
            field=models.TextField(blank=True),
        ),
    ]
