# Generated by Django 4.1.1 on 2023-03-02 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unitymed', '0005_socialmedialinks'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField(blank=True)),
            ],
        ),
    ]
