# Generated by Django 4.1.1 on 2023-03-03 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unitymed', '0008_home_image_home_image_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name_plural': 'About Us'},
        ),
        migrations.AlterModelOptions(
            name='home',
            options={'verbose_name_plural': 'Home'},
        ),
        migrations.AlterModelOptions(
            name='pharmacy',
            options={'verbose_name_plural': 'Pharmacy'},
        ),
        migrations.AlterModelOptions(
            name='socialmedialinks',
            options={'verbose_name_plural': 'Socila Media Links'},
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='title',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='home',
            name='title',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='title',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='service',
            name='keywords',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='socialmedialinks',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
